version: '2'

volumes:
    dkr_pgdata:
        external: true
    dkr_msdata:
        external: true

services:
    dkr_ngx:
        image: nginx:alpine
        container_name: dkr_ngx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./.nginx/hosts/:/etc/nginx/conf.d/
            - ./htdocs:/var/htdocs
            - ./logs:/var/log/
    dkr_apache:
        image: httpd:alpine
        container_name: dkr_apache
        volumes:
            - ./.httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./.httpd/hosts/:/usr/local/apache2/vhosts/
            - ./htdocs:/var/htdocs
            - ./logs:/var/log/
        depends_on:
            - ngx
            - php7fpm
            - postgres
            - msql
        restart: always
    dkr_php7:
        image: php:fpm-alpine
        build: .php
        container_name: dkr_php7
        volumes:
            - ./htdocs:/var/htdocs
            - ./logs:/var/log/
        ports:
            - "9000:9000"
        restart: always
    dkr_postgres:
        image: postgres:alpine
        container_name: dkr_postgres
        ports:
            - "5432:5432"
        volumes:
            - dkr_pgdata:/var/lib/postgresql/data
        restart: always
    dkr_mysql:
        image: mysql:latest
        container_name: dkr_mysql
        ports:
            - "3306:3306"
        volumes:
            - dkr_msdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        restart: always
    dkr_memcached:
        image: memcached:alpine
        container_name: dkr_memcached
        restart: always
    dkr_rabbaitmq:
        image: rabbitmq:alpine
        container_name: dkr_rabbitmq
        restart: always 
    dkr_dns:
        build: .dnsmasq
        container_name: drk_dns
        ports:
            - "127.0.0.2:53:53/udp"
        restart: always

